spring.application.name=ms-usuarios
server.port=8801

spring.datasource.url=jdbc:mysql://3.82.123.219:3306/ms_usuarios
spring.datasource.username=admin
spring.datasource.password=adminpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


jwt.secret=festival-secret-key-2024-muy-larga-para-cumplir-256bits