spring.application.name=ms-logistica
server.port=8805

# Oracle Cloud con Wallet
spring.datasource.url=jdbc:oracle:thin:@msfestival_medium?TNS_ADMIN=C:/Users/diego/Desktop/ProyectoFestival/Wallet_MSFESTIVAL
spring.datasource.username=ms_logistica
spring.datasource.password=Festival12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false
spring.cloud.compatibility-verifier.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=festival-secret-key-2024-muy-larga-para-cumplir-256bits