spring.application.name=ms-logistica
server.port=8802

spring.datasource.url=jdbc:mysql://3.82.123.219:3306/ms_evento
spring.datasource.username=admin
spring.datasource.password=adminpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false
spring.cloud.compatibility-verifier.enabled=false