spring.application.name=ms-tickets
server.port=8804

# Oracle Cloud con Wallet
spring.datasource.url=jdbc:oracle:thin:@msfestival_medium?TNS_ADMIN=C:/Users/k-ort/OneDrive/Desktop/PROYECTO_FESTIVAL/ms-lineup1.1/ms-lineup/wallet
spring.datasource.username=ms_lineup
spring.datasource.password=Festival12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false
spring.cloud.compatibility-verifier.enabled=false

ms.eventos.url=http://localhost:8802
ms.notificaciones.url=http://localhost:8806

jwt.secret=festival-secret-key-2024-muy-larga-para-cumplir-256bits

springdoc.swagger-ui.path=/swagger-ui.html